// <auto-generated />
using System;
using LoginWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoginWeb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250623063728_AddMultiDiskIndexes")]
    partial class AddMultiDiskIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LoginWeb.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommunityString")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("DiskCStorageIndex")
                        .HasColumnType("int");

                    b.Property<int?>("DiskDStorageIndex")
                        .HasColumnType("int");

                    b.Property<int?>("DiskEStorageIndex")
                        .HasColumnType("int");

                    b.Property<int>("HealthStatus")
                        .HasColumnType("int");

                    b.Property<string>("HealthStatusReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastCheckTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastErrorTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OSVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PollingIntervalSeconds")
                        .HasColumnType("int");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<int?>("RamStorageIndex")
                        .HasColumnType("int");

                    b.Property<int>("SnmpVersion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("LoginWeb.Models.DeviceHistory", b =>
                {
                    b.Property<long>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("HistoryId"));

                    b.Property<decimal?>("CpuLoadPercentage")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<decimal?>("DiskUsagePercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("HealthStatus")
                        .HasColumnType("int");

                    b.Property<string>("HealthStatusReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MemoryUsagePercentage")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("PollingStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("SysUpTimeSeconds")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<long?>("TotalDisk")
                        .HasColumnType("bigint");

                    b.Property<long?>("TotalRam")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsedDiskKBytes")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsedRamKBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("WasOnline")
                        .HasColumnType("bit");

                    b.HasKey("HistoryId");

                    b.HasIndex("DeviceId");

                    b.ToTable("DeviceHistories");
                });

            modelBuilder.Entity("LoginWeb.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AccountStatus")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LoginWeb.Models.DeviceHistory", b =>
                {
                    b.HasOne("LoginWeb.Models.Device", "Device")
                        .WithMany("Histories")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("LoginWeb.Models.Device", b =>
                {
                    b.Navigation("Histories");
                });
#pragma warning restore 612, 618
        }
    }
}
